profile: [PROFILE-VALUE]

ceip_policy_disclosed: true

buildservice:
  kp_default_repository: [KP-DEFAULT-REPO]
  kp_default_repository_username: [KP-DEFAULT-REPO-USERNAME]
  kp_default_repository_password: [KP-DEFAULT-REPO-PASSWORD]
  tanzunet_username: [TANZU-NET-USERNAME]
  tanzunet_password: [TANZU-NET-PASSWORD]
  descriptor_name: tap-1.0.0-full
  enable_automatic_dependency_updates: false
  ca_cert_data: |
    -----BEGIN CERTIFICATE-----
    b64-encoded repo certificate only for private repositories
    when using a SaaS based repository the entire ca_cert_data section is not needed
    -----END CERTIFICATE-----

excluded_packages:
  - learningcenter.tanzu.vmware.com
  - workshops.learningcenter.tanzu.vmware.com

supply_chain: basic

ootb_supply_chain_basic:
  registry:
    server: [SERVER-NAME]
    repository: [REPO-NAME]
  gitops:
    ssh_secret: ""

# learningcenter:
#   ingressDomain: .nip.io

# cnrs:
#   domain_name: .nip.io

contour:
  envoy:
    service:
      type: LoadBalancer

tap_gui:
  service_type: LoadBalancer
#  app_config:
#    app:
#      baseUrl: http://.nip.io:7000
#    backend:
#        baseUrl: http://.nip.io:7000
#        cors:
#          origin: http://.nip.io:7000
