profile: full

ceip_policy_disclosed: true

buildservice:
  kp_default_repository: "myrepo/tap120/build-service"
  kp_default_repository_username: "username"
  kp_default_repository_password: "topSecretPassword"
  tanzunet_username: "username@emaildomain.com"
  tanzunet_password: "anotherTopSecretPassword"
  enable_automatic_dependency_updates: false

supply_chain: testing_scanning

ootb_supply_chain_testing_scanning:
  registry:
    server: "index.docker.io"
    repository: "someRepository"

scanning:
  metadataStore:
    url: ""

metadata_store:
  ns_for_export_app_cert: "*"
  app_service_type: NodePort

learningcenter:
  ingressDomain: someDomainName

grype:
  namespace: tst
  targetImagePullSecret: registry-credentials

cnrs:
  domain_name: anotherDomainName

contour:
  envoy:
    service:
      type: LoadBalancer

tap_gui:
  service_type: LoadBalancer
  app_config:
    app:
      baseUrl: http://tapGuiFqdn:7000
    backend:
        baseUrl: http://tapGuiFqdn:7000
        cors:
          origin: http://tapGuiFqdn:7000
    proxy:
      /metadata-store:
        target: https://metadata-store-app.metadata-store:8443/api/v1
        changeOrigin: true
        secure: false
        headers:
          Authorization: "Bearer topSecretToken"
          X-Custom-Source: project-star
